stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

test:
  image: node:22
  stage: test
  before_script:
    - npm install -g pnpm
    - pnpm -r install
    - pnpm -r build
  script:
    - pnpm -r test --coverage
  artifacts:
    reports:
      junit: coverage/web-junit.xml
    paths:
      - coverage/
    expire_in: 1 week
